# Generated by Django 5.0.3 on 2024-03-24 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("floor_id", models.SmallIntegerField(default=0)),
                ("floor_name", models.CharField(max_length=255)),
                ("control_panels", models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Lift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lift_id", models.IntegerField(default=1)),
                ("current_floor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="smartlift.floor")),
            ],
        ),
        migrations.CreateModel(
            name="ServicedFloor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("floor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="smartlift.floor")),
                ("lift", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="smartlift.lift")),
            ],
        ),
        migrations.CreateModel(
            name="LiftRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("COMPLETED", "Completed")], default="PENDING", max_length=10
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("lift", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="smartlift.lift")),
                (
                    "floor_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lift_request_from_floor",
                        to="smartlift.servicedfloor",
                    ),
                ),
                (
                    "floor_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lift_request_from_to",
                        to="smartlift.servicedfloor",
                    ),
                ),
            ],
        ),
    ]
